#!/bin/bash

INPFILE="$1"

if [ ! "$INPFILE" ] || [ ! -e "$INPFILE" ]; then
  echo "File \"$INPFILE\" isn't valid"
  exit 1
fi

NEVS=$(cat "$INPFILE" | sed "s:\s\+: :g" | sed "s:^ ::g" | cut -d " " -f 2 | grep -v "Run" | uniq | wc -l)

echo "$INPFILE contains $NEVS events." 
